Exception ignored in: <bound method PhotoImage.__del__ of <PIL.ImageTk.PhotoImage object at 0x7fef3f411ef0>>
Traceback (most recent call last):
  File "/home/paol/.local/lib/python3.5/site-packages/PIL/ImageTk.py", line 130, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <bound method PhotoImage.__del__ of <PIL.ImageTk.PhotoImage object at 0x7fef3f4117f0>>
Traceback (most recent call last):
  File "/home/paol/.local/lib/python3.5/site-packages/PIL/ImageTk.py", line 130, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
